---
job: extension
config:
  name: "lora_name"
  process:
    - type: 'sd_trainer'
      training_folder: "/content/Lora"
      device: cuda:0
      trigger_word: "p3r5on"
      network:
        type: "lora"
        linear: 16
        linear_alpha: 16
      save:
        dtype: float16 
        save_every: 350
        max_step_saves_to_keep: 100 
        push_to_hub: false 
      datasets:
        - folder_path: "/content/"
          caption_ext: "txt"
          caption_dropout_rate: 0.05  
          shuffle_tokens: false  
          cache_latents_to_disk: true  
          resolution: [ 512, 768, 1024 ]
      train:
        batch_size: 1
        steps: 1400
        gradient_accumulation_steps: 1
        train_unet: true
        train_text_encoder: false  
        gradient_checkpointing: true  
        noise_scheduler: "flowmatch"
        optimizer: "adamw8bit"
        lr: 4e-4
        lr_scheduler: "cosine"
        lr_scheduler_params:
          total_iters: 4000  # Tổng số step training
          eta_min: 4e-5      # LR tối thiểu (đích cần giảm về)
        ema_config:
          use_ema: true
          ema_decay: 0.99
        dtype: bf16
        skip_first_sample: false
        disable_sampling: false
      model:
        name_or_path: "black-forest-labs/FLUX.1-dev"
        is_flux: true
        quantize: true  
        low_vram: true
      sample:
        sampler: "flowmatch" 
        sample_every: 350
        width: 1820
        height: 1024
        prompts:
          - "The image depicts a cozy, warmly lit café interior on a snowy evening, exuding a sense of tranquility and charm. The café features a rustic wooden design with soft yellow lighting from chandeliers and hanging lamps, creating an inviting atmosphere. Large glass windows reveal a serene winter landscape with bare trees and softly glowing lights in the distance, complementing the cozy interior. A polished wooden counter is adorned with various items, including coffee jars, filters, and a professional espresso machine, while a bar area with stools offers patrons a perfect spot to enjoy the snowy view. In the foreground, a small round table is set with two coffee cups, a candle, a folded blanket on a wooden chair, and a centerpiece featuring flowers and pinecones. The décor includes chalkboard menus, a "Jazz Café" poster with a piano-themed design, and shelves filled with jars, cups, plates, and decorative items. Scattered throughout are candles, open books, pancakes, pastries, and nuts, adding warmth and detail to the space. The thoughtful arrangement of natural accents, such as pinecones and fresh flowers, enhances the inviting atmosphere, making it an ideal setting for a relaxing winter evening"
        neg: "" 
        seed: 42
        walk_seed: true
        guidance_scale: 3.5 
        sample_steps: 28
meta:
  name: "lora_name"
  version: '1.0'
